-- Run this in the Supabase SQL Editor

-- 1. Create the table
create table public.burndown_logs (
  id bigint generated by default as identity primary key,
  date date not null,
  member text not null,
  remaining_hours numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_entry unique (date, member)
);

-- 2. Enable Realtime (optional but recommended for syncing)
alter publication supabase_realtime add table public.burndown_logs;

-- 3. Policy (RLS) - For now, allow public read/write for simplicity
-- WARNING: In production, add auth logic!
alter table public.burndown_logs enable row level security;

create policy "Public Access"
on public.burndown_logs
for all
using (true)
with check (true);
